$${% block jobs %}
$${ super() }
$${% if publish %}
  build-homebrew:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install pyinstaller

      - name: Run PyInstaller build script
        run: bash scripts/build.sh

      - name: Create binary tarball
        run: tar -czf multi.tar.gz -C dist/multi .

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: multi-binary
          path: multi.tar.gz
          retention-days: 5

      - name: Upload to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: multi.tar.gz

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          token: ${{secrets.GH_TOKEN}}
          no_fork: true
          tap: $${homebrew_tap_location}
          formula: cursor-multi
$${% endif %}
$${% endblock %}
